version: '3.8'

services:
  postgresql:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: 123mohamed
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Connect to Zookeeper service


  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
